version: '3.7'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.3
    container_name: filebeat
    user: root
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    volumes:
      - '/home/ec2-user/monitoring/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    depends_on:
      - redis-cache
  redis-cache:
    image: redis:latest
    container_name: redis
    ports: 
      - 6379:6379